version: '3.3'

services:
  hackerlab:
    build: ./hackerlab
    container_name: hackerlab
    hostname: hackerlab
    restart: always
    networks:
      playground-net:
        ipv4_address: 172.20.0.2

  submission-server:
    build: ./submission-server
    container_name: submission-server
    hostname: submission-server
    restart: always
    networks:
      playground-net:
        ipv4_address: 172.20.0.3
    volumes:
      - ./challenges:/challenges

  hello-world:
    build: ./challenges/hello-world
    networks:
      playground-net:
        ipv4_address: 172.20.0.5

  famous-quotes-lfi:
    build: ./challenges/famous-quotes-lfi
    networks:
      playground-net:
        ipv4_address: 172.20.0.10

networks:
  playground-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24
          gateway: 172.20.0.1